paragonie/sodium_compat

README.md, src/Compat.php, src/Core/SipHash.php, tests/compat/SodiumCompatTest.php, tests/unit/Blake2bTest.php, tests/unit/Poly1305Test.php, tests/unit/Salsa20Test.php, tests/unit/SipHashTest.php
Closes #6 
Note that this was slightly more challenging than a direct port because I chose to make it only use 32-bit integers and SipHash was designed with 64-bit integers in mind.
The reason for choosing to use 32-bit integers is that many PHP 5 users do not have access to 64-bit integers, and if we want maximum compatibility (see #1), we have to make sure it will work on these platforms.
=> Siphash-2-4 (32-bit)

README.md, src/Compat.php, src/Crypto.php, tests/compat/SodiumCompatTest.php
Closes #7 -- this is actually just the leftmost 256 bits of HMAC-SHA512.
=> Crypto_auth

.travis.yml, composer.json, composer.lock, lib/sodium_compat.php, psalm.xml, src/Compat.php, src/Core/BLAKE2b.php, src/Core/Curve25519.php, src/Core/Curve25519/Fe.php, src/Core/Curve25519/Ge/Cached.php, src/Core/Curve25519/Ge/P1p1.php, src/Core/Curve25519/Ge/P2.php, src/Core/Curve25519/Ge/P3.php, src/Core/Curve25519/Ge/Precomp.php, src/Core/Ed25519.php, src/Core/Salsa20.php, src/Core/Util.php, src/Core/X25519.php, src/Core/Xsalsa20.php, src/Crypto.php, tests/compat/SodiumCompatTest.php
Some of the INFO notices produced are the result of bugs or inconsistencies in Psalm itself, so we're suppressing them.
That said, using [Psalm](https://github.com/vimeo/psalm) for static analysis during Travis CI is a great way to validate new code.
=> Integrate with psalm (PHP static analysis tool)

src/Core/Util.php
So, to be more constructive than my last PR, here's a simple one.
I know I've PR'd the same thing on other repos, but it really is the right way to do it.
function_exists() is the wrong way to check for an extension. Someone could have a shim. And then we're depending on their shim (iconv) to do string operations correctly.
=> Fix mbstring compat.

src/Core/Ed25519.php, src/File.php, tests/unit/FileTest.php
To reduce the memory requirements for Ed25519 verification, we use a streaming API to calculate the same result. I'm not confident that this should be included in v0.3.0, but some projects may desire this if v1.0.0 is ever tagged.
=> Proposal: Streaming Ed25519 verification

src/Core/Ed25519.php
The same message was copied into 3 places, while second and third are keypairs rather than seed.
=> Typo in exceptions messages

src/Core/Ed25519.php
=> Unnecessary `substr()` call, exact length already checked few lines earlier

.travis.yml
Opt in to trusty early to fix hhvm, hold php5.3 on precise. Should open a bug to remove `dist: trusty` when travis makes the switch. 5.3 needs to be locked on precise though.
=> Fix HHVM, prepare PHP 5.3 test for travis switch.

src/Compat.php
I'll need to rename this method from `isPhp72OrGreater()` to something more descriptive. See #68
=> Proposed fix for #68

.travis.yml
The newest version of Psalm introduced a bug with polyfilled classes. While I work on fixing that bug, this PR reverts to the newest-but-one version of Psalm. Apologies!
=> Use specific versions of Psalm

src/Compat.php
Pass the value by reference to \Sodium\memzero() and ensure the value seems to have been wiped to not silent an issue.
This is related to #73.
Using the same strategy with `\Sodium\increment()` or variants of it with `call_user_func_array()` or `ReflectionFunction::invokeArgs()` does not seem to work. I'm not quite sure why at the moment.
=> Ensure sodium_memzero() wipe the string when libsodium-php 1.x is used

src/Core32/Int64.php, tests/Int64TestTemp.php, tests/Windows32Test.php, tests/unit/Int64Test.php
Makes `ParagonIE_Sodium_Compat::$fastMult` actually do something on
32-bit platforms.
=> 32-bit curve25519 speedup (important for WordPress)

.travis.yml
Maybe I should use a dedicated variable.
`composer self-update` is already included in TravisCI.
=> WIP: Let's see phpstan in CI

LICENSE, autoload-phpunit.php, composer.json, src/Core/BLAKE2b.php, src/Core32/BLAKE2b.php, tests/Windows32Test.php
Internal state was being constructed with the incorrect byte order.
This PR also attempts to support PHPUnit 6 and 7 in all versions of PHP (if applicable).
=> Fix for BLAKE2b on 32-bit platforms

src/Core/Ed25519.php, src/Core32/Ed25519.php
There are more inclusive terms that can be used instead. This PR changes all occurrences of "blacklist" to "blocklist".
Part of the efforts in https://core.trac.wordpress.org/ticket/50413.
=> Remove the term "blacklist"

.travis.yml, src/Core/Util.php
On php 8, the `MB_OVERLOAD_STRING` constant has been removed together with the mbstring function overload feature. In order to avoid an error when accessing the constant, I've saveguarded the access with a `defined()` call.
=> Bugfix: mbstring function overloading has been removed in php 8

autoload.php, src/Core/BLAKE2b.php, src/Core32/BLAKE2b.php
Possible fix for #122 by coercing the autoloader to always load the `ParagonIE_Sodium_Compat` class before the remaining polyfills (constants, etc.).
=> Coerce the autoloading of the primary class

.github/workflows/ci.yml, .github/workflows/psalm.yml
I came to send in PR #134 and to turn on testing against PHP 8.1, I stayed to make a lot more fixes to the CI workflows... 😂 
TL;DR: The tests on PHP 5.3-5.6 were not running at all, which meant that it was missed that the changes in commit 8e0e0210fe6e0d816de4effd62e9bcbc20fe9889 are not compatible with PHP < 7.0.
Turning the tests on, now exposes this.
Please check out the various commit messages and the action run results to get the full picture.
... use `ubuntu-18.04` or `ubuntu-latest` for `20.04` instead.
Also see:
* https://ubuntu.com/blog/ubuntu-16-04-lts-transitions-to-extended-security-maintenance-esm
* shivammathur/setup-php#452
As no code coverage is being recorded for these builds, it is good practice to explicitly set `coverage: none` in `setup-php`.
This fixes a warning …
=> GH Actions: fix the workflows

src/Core/ChaCha20/Ctx.php, src/Core/Curve25519/Fe.php, src/Core32/ChaCha20/Ctx.php, src/Core32/Curve25519/Fe.php
As of PHP 8.1, PHP will start throwing deprecation warnings along the lines of:
```
Deprecated:  Return type of [CLASS]::[METHOD]() should either be compatible with [PHP NATIVE INTERFACE]::[METHOD](): [TYPE], or the #[ReturnTypeWillChange] attribute should be used to temporarily suppress the notice
```
These type of deprecation notices relate to the [Return types for internal methods RFC](https://wiki.php.net/rfc/internal_method_return_types) in PHP 8.1.
Basically, as of PHP 8.1, these methods in classes which implement PHP native interfaces are expected to have a return type declared.
The return type can be the same as used in PHP itself or a more specific type. This complies with the Liskov principle of covariance, which allows the return type of a child overloaded method to be more …
=> PHP 8.1: fix deprecation warnings

.github/workflows/ci.yml, .github/workflows/psalm.yml
The action used to install Composer packages and handle the caching has released a new major (and some follow-up patch releases), which means, the action reference needs to be updated to benefit from it.
Refs:
* https://github.com/ramsey/composer-install/releases/tag/2.0.0
* https://github.com/ramsey/composer-install/releases/tag/2.0.1
* https://github.com/ramsey/composer-install/releases/tag/2.0.2
* https://github.com/ramsey/composer-install/releases/tag/2.0.3
=> GH Actions: version update for `ramsey/composer-install`

.github/workflows/ci.yml, .github/workflows/psalm.yml
A number of predefined actions have had major release, which warrant an update to the workflow(s).
These updates don't actually contain any changed functionality, they are mostly just a change of the Node version used by the action itself (from Node 14 to Node 16).
Refs:
* https://github.com/actions/checkout/releases
=> GH Actions: version update for various predefined actions

autoload.php
This may help with errors induced by opcache preloading.
#148
=> Less reliance on include guards that return early

autoload-fast.php, autoload-pedantic.php
Without the directory if the file autoload.php exists in a location on the load path prior it will be loaded instead causing errors.
=> Adds directory to require_once calls.

lib/php72compat.php, lib/ristretto255.php, lib/sodium_compat.php, psalm-above-3.xml, psalm-below-3.xml
This is technically an API break for PHP 8 projects. However, this polyfill always targeted PHP 5, 7.0, and 7.1. You shouldn't need it on 7.2+.
The end result of this change is that you should be able to write code that uses named parameters on PHP 8 and have it work regardless of ext/sodium being installed or not (provided you import sodium_compat via composer).
Additionally, we include lib/ in the psalm checks (if applicable).
This will need a new minor version (v1.19.0).
=> Fix variable names to match ext/sodium

.github/workflows/ci.yml
PHP 8.2 has long been released and PHP 8.3 is nearing the first RC, so I propose adding PHP 8.3 to the matrix and no longer allowing PHP 8.2 to fail the build.
Additional notes:
* As the build against PHP 8.3 passes, I've not added a `continue-on-error` allowance for PHP 8.3.
* As all dependencies install okay on PHP 8.3, I've removed the toggle to `composer install` with `--ignore-platform-reqs`.
=> GH Actions: update PHP versions in workflows

.github/workflows/ci.yml, lib/php72compat.php, src/Compat.php, src/Core/AEGIS/State128L.php, src/Core/AEGIS/State256.php, src/Core/AEGIS128L.php, src/Core/AEGIS256.php, src/Core/AES.php, src/Core/AES/Block.php, src/Core/AES/Expanded.php, src/Core/AES/KeySchedule.php, src/Core/Util.php, tests/compat/PHP84Test.php, tests/unit/AEGISTest.php, tests/unit/AESTest.php, tests/unit/UtilTest.php
Fixes #162 when merged.
RFC: https://datatracker.ietf.org/doc/draft-irtf-cfrg-aegis-aead
This is the first step towards implementing AEGIS-128L and AEGIS-256 in pure PHP, with the eventual hope of polyfilling those functions ahead of their landing in PHP 8.4's ext-sodium.
While we *may* be able to use a table look-up version of AES for the actual bulk data processing for AEGIS, we do _at least_ want a bitsliced implementation of the AES round function for the Init() step.
This implementation is based heavily on the work of Thomas Pornin's BearSSL project.
See https://www.bearssl.org/constanttime.html#aes
We specified an aesRound method on ParagonIE_Sodium_Core_AES that uses our bitsliced AES implementation to perform one round with an arbitrary round key (rather than relying on the key …
=> AEGIS Implementation

README.md
Following our discussion [here](https://old.reddit.com/r/PHP/comments/1c6o04x/does_anyone_still_need_php_5_support_in_2024/), we believe this should be the best step forward.
WordPress, which cares a lot about environments where `PHP_INT_SIZE == 4`, can continue to use v1.x if they prefer.
We plan on backporting any fixes from v2.x to v1.x as needed, but don't anticipate many.
=> New major version policy

dist/box.json
Since we no longer need random_compat, we can remove this.
=> Remove vendor/paragonie from box.json

lib/php72compat.php, lib/php84compat.php, lib/ristretto255.php, lib/sodium_compat.php, lib/stream-xchacha20.php, src/Compat.php, src/File.php
In PHP 8.2 and newer, this attribute is used to mark parameters that are sensitive and should be redacted from stack traces.
This has no effect on PHP 8.1 or older, but is a nice-to-have for PHP 8.2+.
=> [v1] Use SensitiveParameter on public API

composer.json
this way, when running on a 32bits version of PHP, Composer will know it cannot use those releases (too bad this was not done in the 2.0.0 release)
=> Make composer aware of the requirement for 64bits PHP

src/Compat.php
Implicitly marking it as nullable is deprecated starting with PHP 8.4.
=> explicitly mark argument $alg as nullable

composer.json
Defining the branch alias allows projects to test recent additions before they are part of a tagged release.
=> define 2.0.x-dev as an alias for the master branch

src/Core/AES/Block.php, src/Core/Curve25519/Fe.php
Found a few more nits that could impact PHP 8.4
=> PHP 8.4 compat nits

.github/workflows/ci.yml
If this passes without deprecation warnings, #186 is fixed.
=> Test PHP 8.5 in CI on v1.x

src/Core/Curve25519.php, src/Core/Curve25519/Fe.php, src/Core/X25519.php
This is a backport of #198 to the v1.x branch. It's not a 1:1 copy, as some code style changes occur in PHP 8.1+.
| PHP Version | *This Pull Request* | [v1.22.0](https://github.com/paragonie/sodium_compat/actions/runs/18122379545) | [v1.21.1](https://github.com/paragonie/sodium_compat/actions/runs/17863860186) |
|------|-------|-------|------|
| 5.3 | **1.92 minutes** | 2.11 minutes | 2.12 minutes |
| 5.4 | **1.54 minutes** | 1.8 minutes | 1.71 minutes |
| 5.5 | **1.33 minutes** | 1.64 minutes | 1.64 minutes |
| 5.6 | **1.24 minutes** | 1.54 minutes | 1.53 minutes |
| 7.0 | **38.43 seconds** | 46.38 seconds | 44.93 seconds |
| 7.1 | **31.86 seconds** | 36.24 seconds | 35.78 seconds |
| 7.2 | **41.27 seconds** | 45.9 seconds | 45.77 seconds |
| 7.3 | **00:41.152** | 00:45.740 | 00:46.385 | …
=> Backport #198 to v1.x

src/Core/Util.php, tests/unit/UtilTest.php
Since sodium_compat v2 requires PHP 8.1+, we can remove some codes.
- Function overload feature of mbstring was removed as of PHP 8.0.
- Starting from PHP 8.0, `substr($str, $offset, null)` has same effect as `substr($str, $offset)`.
Also adding a test case of omitting the third parameter of `substr`.
=> Remove dead or redundant code of `Util::(strlen|substr)`
