paragonie/sodium_compat

lib/sodium_compat.php, src/Compat.php, src/Core/BLAKE2b.php, src/Core/ChaCha20.php, src/Core/ChaCha20/Ctx.php, src/Core/ChaCha20/IetfCtx.php, src/Core/Util.php, src/Crypto.php, tests/compat/SodiumCompatTest.php, tests/unit/ChaCha20Test.php, tests/unit/CryptoTest.php
=> Implement ChaCha20-Poly1305

src/Compat.php
https://twitter.com/chrisleppanen/status/821974666600333312
=> Fix comma.

.gitignore, autoload.php, composer.json, src/Compat.php, src/Core/Ed25519.php, src/File.php, tests/unit/Ed25519Test.php, tests/unit/FileTest.php, tests/unit/HSalsa20Test.php, tests/unit/X25519Test.php, tests/unit/Xsalsa20Test.php
Closes #19. After this branch is merged, we're freezing the code in anticipation for #8.
Please direct any complaints about the current code quality in this issue.
=> Internal Code Review Before v0.3.0

tests/unit/Ed25519Test.php
https://www.rfc-editor.org/rfc/rfc8032.txt
=> Add test vectors from RFC 8032

.travis.yml, autoload-fast.php, lib/php72compat.php, lib/sodium_compat.php, src/Compat.php, src/Core/BLAKE2b.php, src/Core/Curve25519.php, src/Core/Ed25519.php, src/Core/Util.php, src/Core/X25519.php, src/Crypto.php, src/File.php, tests/unit/FileTest.php
Exactly what it says on the label.
=> PHP 7.2 Compatibility, Cleanup

src/File.php, tests/unit/FileTest.php
In case anyone needs/wants a BLAKE2b checksum of a file.
=> Implement ParagonIE_Sodiuim_File::generichash()

README.md, psalm.xml, src/Compat.php, src/Core/BLAKE2b.php, src/Core/ChaCha20.php, src/Core/ChaCha20/Ctx.php, src/Core/Curve25519.php, src/Core/Curve25519/Fe.php, src/Core/Curve25519/H.php, src/Core/Ed25519.php, src/Core/Poly1305/State.php, src/Core/Salsa20.php, src/Core/SipHash.php, src/Core/Util.php, src/Core/X25519.php, src/Core32/BLAKE2b.php, src/Core32/ChaCha20.php, src/Core32/ChaCha20/Ctx.php, src/Core32/Curve25519.php, src/Core32/Curve25519/Fe.php, src/Core32/Curve25519/H.php, src/Core32/Ed25519.php, src/Core32/HChaCha20.php, src/Core32/Int32.php, src/Core32/Int64.php, src/Core32/Poly1305/State.php, src/Core32/X25519.php, src/File.php
This makes tests pass with `totallyTyped="true"`.
=> Type safety

src/File.php, tests/Windows32Test.php, tests/windows-test.bat
=> Fix the 32-bit implementation

lib/php72compat.php, src/Compat.php
See https://github.com/paragonie/paseto/issues/98
=> Fallback to ext/sodium for XChaCha20-Poly1305 if available.

src/Compat.php, tests/unit/CompatTest.php
Ref https://core.trac.wordpress.org/ticket/47186#comment:32
=> Add ParagonIE_Sodium_Compat::runtime_speed_test()

.travis.yml
https://docs.travis-ci.com/user/reference/trusty/#php-images
=> Modern Travis images do not support PHP 5.4, 5.5

autoload-phpstan.php, phpstan.neon.dist
@paragonie-scott 
Plus a quick cleanup in the config file.
=> phpstan is very happy loading multiple files

src/Core/Ed25519.php, src/Core32/Ed25519.php, src/File.php
Based off https://github.com/jedisct1/libsodium/pull/884 which is,
in turn, based off https://github.com/dalek-cryptography/ed25519-dalek/pull/99
Thanks @isislovecruft
=> Optimize Ed25519 verification.

autoload-php7.php, autoload.php
=> Proposed fix for #116

LICENSE
This will make github recognise the licence
=> Normalise licence

src/Core/Ed25519.php, src/Core32/Ed25519.php
=> Guarantee Curve25519 is loaded from Ed25519

lib/php72compat.php, src/Compat.php, src/Core/Util.php, tests/unit/HexTest.php
This parameter was discovered to be missing in our polyfill
=> Add ignore to sodium_hex2bin()

README.md, src/Core/AEGIS/State128L.php, src/Core/AEGIS/State256.php, src/Core/AES.php, src/Core/AES/Expanded.php, src/Core/AES/KeySchedule.php, tests/unit/AESTest.php
This is just an assortment of pre-release boy-scouting.
=> Pre v1.21 fixes

.gitattributes, .github/workflows/ci.yml, .github/workflows/fuzz.yml, .github/workflows/mutation.yml, .github/workflows/psalm.yml, CONTRIBUTING.md, composer.json, fuzzing/FuzzSodiumCompat.php, infection.json.dist, phpunit.xml.dist, psalm-new.xml, src/Compat.php, tests/compat/Ristretto255CompatTest.php, tests/unit/AEGISTest.php, tests/unit/AESTest.php, tests/unit/Aes256GcmTest.php, tests/unit/CompatTest.php, tests/unit/CryptoTest.php, tests/unit/FileTest.php, tests/unit/HexTest.php, tests/unit/Ristretto255Test.php, tests/unit/UtilTest.php
This pull request adds fuzz-testing and mutation testing to the CI pipeline when releases are tagged. It also increases unit test coverage in response to the mutation tests. We also bump the supported range of testing frameworks.
=> Improve Assurance of Sodium_Compat

tests/unit/UtilTest.php
The latest PR merge failed unexpectedly.
=> Fix flaky test for PHP 8.1+

src/Compat.php, src/Core/Base64/Original.php, src/Core/Base64/UrlSafe.php, src/Core/ChaCha20/Ctx.php, src/Core/ChaCha20/IetfCtx.php, src/Core/Util.php, tests/unit/UtilTest.php
Backport the relevant non-test changes from #194
=> Backport fixes from v2.x
